apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-springboot-thyqizlm
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-springboot-thyqizlm:175a9ac8322146ba5ac4dccf326aeccd66824a0e@sha256:4f79235ee242788251c097bf8110f0c792800e90cb90be95f32d1d6f3c6e71db
          name: container-image
